pull_request_rules:
- actions:
    merge:
      strict: true
  conditions:
  - base=20210929095143/test_merge_strict_default/main
  - status-success=continuous-integration/fake-ci
  - '#approved-reviews-by>=1'
  name: smart strict merge on main
