pull_request_rules:
- actions:
    merge:
      commit_message_template: '{{ title }} (#{{ number }})

        {{body}}

        superRP!

        '
  conditions:
  - base=20211109134459/test_merge_template/main
  name: merge on main
