pull_request_rules:
- actions:
    merge:
      priority: high
      strict: smart+ordered
  conditions:
  - base=20211104123840/test_commit_message_brownout/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
