pull_request_rules:
- conditions:
  - base=20210929092806/test_merge_template/main
  merge:
    commit_message: template
    template_commit_message: "{{ title }} (#{{ number }})\n                    {{body}}\n\
      \n                    super RP!\n                    "
  name: merge on main
