pull_request_rules:
- actions:
    review:
      message: Thank you {{hello}}
      type: REQUEST_CHANGES
  conditions:
  - base=20210916100120/test_review_template_attribute_error/main
  name: review
