pull_request_rules:
- actions:
    merge:
      commit_message: template
      template_commit_message: '{{ title }} (#{{ number }})

        {{body}}

        superRP!

        '
  conditions:
  - base=20211011131328/test_merge_template/main
  name: merge on main
